# Site settings
title:BIVisuals | Power BI
email: hello@bivisuals.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "bivisuals.com" # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
markdown: kramdown
